// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Hello():Promise<string>;

export function OpenFileDlg():Promise<string>;

export function ReadImage():Promise<Array<number>>;

export function Startup(arg1:context.Context):Promise<void>;
