// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hello() {
  return window['go']['gateway']['ImageApp']['Hello']();
}

export function OpenFileDlg() {
  return window['go']['gateway']['ImageApp']['OpenFileDlg']();
}

export function ReadImage() {
  return window['go']['gateway']['ImageApp']['ReadImage']();
}

export function Startup(arg1) {
  return window['go']['gateway']['ImageApp']['Startup'](arg1);
}
