// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {global} from '../models';
import {systemModel} from '../models';
import {context} from '../models';

export function Load():Promise<global.ResponseT>;

export function Save(arg1:systemModel.Setting):Promise<global.ResponseT>;

export function Startup(arg1:context.Context):Promise<void>;
