// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['gateway']['TodoController']['Delete'](arg1);
}

export function Finish(arg1) {
  return window['go']['gateway']['TodoController']['Finish'](arg1);
}

export function Load() {
  return window['go']['gateway']['TodoController']['Load']();
}

export function Save(arg1) {
  return window['go']['gateway']['TodoController']['Save'](arg1);
}

export function Startup(arg1) {
  return window['go']['gateway']['TodoController']['Startup'](arg1);
}
