// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1, arg2) {
  return window['go']['gateway']['UserController']['Login'](arg1, arg2);
}

export function Me(arg1, arg2) {
  return window['go']['gateway']['UserController']['Me'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['gateway']['UserController']['Startup'](arg1);
}
